
development:
  adapter: postgresql
  encoding: unicode
  database: authtest_development
  pool: 5
  username: abruzzim
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: authtest_test
  pool: 5
  username: abruzzim
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: authtest_production
  pool: 5
  username: abruzzim
  password:
